### PR TITLE
User post component

### PR DESCRIPTION
**Pull request by GenedyMohamed**
Back-end and Front-end. Everything is tested.

### CODE REVIEW

**Comment by GenedyMohamed** [comment]
Admin needs to accept the component and be able to add a category

**Review by hossamElfar — COMMENTED** [review]
Please restore .env.example

**Comment by GenedyMohamed** [comment]
Done

**Comment by GenedyMohamed** [comment]
Added admin add edit delete

**Comment by GenedyMohamed** [comment]
Now admin can accept reject or delete components from the admin panel

**Pull request merged**
